// REST endpoint definitions

export const API_ROUTES = {
	AUTH: {
		REGISTER: "/auth/register",
		LOGIN: "/auth/login",
		LOGOUT: "/auth/logout",
		VERIFY_OTP: "/auth/verify-otp",
		VERIFY_RESET_OTP: "/auth/verify-reset-otp",
		RESEND_REGISTER_OTP: "/auth/resend-otp",
		RESET_PASSWORD: "/auth/reset-password",
		RESEND_RESET_OTP: "/auth/resend-reset-otp",
		UPDATE_PASSWORD: "/auth/update-password",
		GOOGLE: "/auth/google",
		REFRESH: "/auth/refresh",
		ADD_INTERESTS: "/auth/add-interests",
		GET_USER: "/auth/me",
	},
	USERMANAGEMENT: {
		USERS: "/users",
		BLOCK: (id: string) => `/users/block/${id}`,
		UNBLOCK: (id: string) => `/users/unblock/${id}`,
	},
	EXPERTISE: {
		CREATE: "/expertise/",
		FETCH: "/expertise",
		FETCH_BY_ADMIN: "/expertise/admin",
		ACTIVE: "/expertise/active",
		UPDATE: (expertiseId: string) => `/expertise/${expertiseId}`,
		VERIFY: (expertiseId: string) => `/expertise/${expertiseId}/verify`,
		CREATE_SKILL: (id: string) => `/expertise/${id}/skills`,
		UPDATE_SKILL: (skillId: string) => `/expertise/skills/${skillId}`,
		VERIFY_SKILL: (skillId: string) => `/expertise/skills/${skillId}/verify`,
		FETCH_SKILLS: (expertiseId: string) => `/expertise/${expertiseId}/skills`,
		FETCH_SKILLS_BY_ADMIN: (expertiseId: string) => `/expertise/${expertiseId}/skills/admin`,
		FETCH_SKILLS_BY_AREAS: "/expertise/skills",
	},
	MENTOR: {
		FETCH: "/mentor",
		FETCH_MENTORS_FOR_USER: "/mentor/user",
		UPDATE: "/mentor",
		CREATE: "/mentor",
		APPROVE: `/mentor/approve`,
		REJECT: `/mentor/reject`,
		FETCH_SINGLE: (mentorId: string) => `/mentor/${mentorId}`,
		GETME: "/mentor/getMe"
	},
	ARTICLES: {
		ARTICLES: "/articles",
		CREATE: "/articles",
		FETCH: (id: string) => `/articles/${id}`,
		UPDATE: `/articles`,
		DELETE: (id: string) => `/articles/${id}`,
		READ: (id: string) => `/articles/${id}`,
		ARTICLES_BY_CATEGORY: "/articles/by-category",
	},
	TAGS: {
		FETCH_MOST_USED: "/tags/most-used",
	},
	MEDIA: {
		GENERATE_TOKEN: "/media/generate-signature",
		SAVE_MEDIA: "/media/save-media",
		DELETE: (id: string, mediaType: string) => `/media/${id}/${mediaType}`,
	},
	REACT: {
		REACT_RESOURCE: "/reactions",
		GET_REACTIONS: "/reactions",
	},
	COMMENT: {
		BASE: "/comments",
	},
	PROFILE: {
		FETCH: (userId: string) => `/profile/${userId}`,
		UPDATE: "/profile",
		UPDATE_PASSWORD: "/profile/change-password",
	},
	NOTIFICATIONS: {
		MARK_READ: (notificationId: string) => `/notifications/${notificationId}`,
		MARK_ALL_AS_READ: "/notifications/mark-all",
		FETCH: "/notifications",
	},
	CONNECTIONS: {
		FOLLOW: "/connection/follow",
		FETCH_FOLLOWERS: "/connection/followers",
		FETCH_FOLLOWING: "/connection/following",
		UNFOLLOW: "/connection/unfollow",
		RECENT_ACTIVITY: "/connection/recent-activity",
		SUGGGESTED: "/connection/suggested",
		MUTUAL: "/connection/mutual",
	},
	CHATS: {
		FETCH: "/chat",
		FETCH_CHAT: (chatId: string) => `/chat/${chatId}`,
	},
	SLOTS: {
		GET_RULES: `/slots/rules`,
		CREATE_RECURRING_RULE: `/slots/availability/recurring`,
		UPDATE_RECURRING_RULE: (ruleId: string) => `/slots/availability/recurring/${ruleId}`,
		ADD_RECURRING_RULE: `/slots/availability/recurring/create`,
		DISABLE_RECURRING_RULE: (ruleId: string) => `/slots/availability/recurring/${ruleId}/disable`,
		DELETE_RECURRING_RULE: (ruleId: string) => `/slots/availability/recurring/${ruleId}/delete`,
		CREATE_CUSTOM_SLOT: `/slots/availability/custom`,
		GET_MENTOR_SLOTS: `/slots/slots`,
		CANCEL_SLOT: (slotId: string) => `/slots/${slotId}/cancel`,
	},
	SESSIONS: {
		BOOK_SESSION: (slotId: string) => `/sessions/${slotId}/book`,
		CANCEL_BOOKING: (bookingId: string) => `/sessions/${bookingId}/cancel`,
		START_SESSION: (slotId: string) => `/sessions/${slotId}/start`,
		MARK_SESSION_AS_COMPLETED: (sessionId: string) => `/sessions/${sessionId}/complete`,
	}
} as const;
