/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as authenticatedRouteRouteImport } from './routes/(authenticated)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UnauthorizedIndexRouteImport } from './routes/unauthorized/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as authenticatedSessionsRouteImport } from './routes/(authenticated)/sessions'
import { Route as authenticatedProfileRouteImport } from './routes/(authenticated)/profile'
import { Route as authenticatedNotificationsRouteImport } from './routes/(authenticated)/notifications'
import { Route as authenticatedMentorsRouteImport } from './routes/(authenticated)/mentors'
import { Route as authenticatedHomeRouteImport } from './routes/(authenticated)/home'
import { Route as authenticatedArticlesRouteImport } from './routes/(authenticated)/articles'
import { Route as AdminUsermanagementIndexRouteImport } from './routes/admin/usermanagement/index'
import { Route as AdminMentormanagementIndexRouteImport } from './routes/admin/mentormanagement/index'
import { Route as AdminExpertisemanagementIndexRouteImport } from './routes/admin/expertisemanagement/index'
import { Route as AdminDashboardIndexRouteImport } from './routes/admin/dashboard/index'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedRouteRoute = authenticatedRouteRouteImport.update({
  id: '/(authenticated)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedIndexRoute = UnauthorizedIndexRouteImport.update({
  id: '/unauthorized/',
  path: '/unauthorized/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const authenticatedSessionsRoute = authenticatedSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authenticatedProfileRoute = authenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authenticatedNotificationsRoute =
  authenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedMentorsRoute = authenticatedMentorsRouteImport.update({
  id: '/mentors',
  path: '/mentors',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authenticatedHomeRoute = authenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authenticatedArticlesRoute = authenticatedArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const AdminUsermanagementIndexRoute =
  AdminUsermanagementIndexRouteImport.update({
    id: '/usermanagement/',
    path: '/usermanagement/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminMentormanagementIndexRoute =
  AdminMentormanagementIndexRouteImport.update({
    id: '/mentormanagement/',
    path: '/mentormanagement/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminExpertisemanagementIndexRoute =
  AdminExpertisemanagementIndexRouteImport.update({
    id: '/expertisemanagement/',
    path: '/expertisemanagement/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminDashboardIndexRoute = AdminDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof authenticatedRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/articles': typeof authenticatedArticlesRoute
  '/home': typeof authenticatedHomeRoute
  '/mentors': typeof authenticatedMentorsRoute
  '/notifications': typeof authenticatedNotificationsRoute
  '/profile': typeof authenticatedProfileRoute
  '/sessions': typeof authenticatedSessionsRoute
  '/admin/': typeof AdminIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/unauthorized': typeof UnauthorizedIndexRoute
  '/admin/dashboard': typeof AdminDashboardIndexRoute
  '/admin/expertisemanagement': typeof AdminExpertisemanagementIndexRoute
  '/admin/mentormanagement': typeof AdminMentormanagementIndexRoute
  '/admin/usermanagement': typeof AdminUsermanagementIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof authenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/articles': typeof authenticatedArticlesRoute
  '/home': typeof authenticatedHomeRoute
  '/mentors': typeof authenticatedMentorsRoute
  '/notifications': typeof authenticatedNotificationsRoute
  '/profile': typeof authenticatedProfileRoute
  '/sessions': typeof authenticatedSessionsRoute
  '/admin': typeof AdminIndexRoute
  '/auth': typeof AuthIndexRoute
  '/unauthorized': typeof UnauthorizedIndexRoute
  '/admin/dashboard': typeof AdminDashboardIndexRoute
  '/admin/expertisemanagement': typeof AdminExpertisemanagementIndexRoute
  '/admin/mentormanagement': typeof AdminMentormanagementIndexRoute
  '/admin/usermanagement': typeof AdminUsermanagementIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(authenticated)': typeof authenticatedRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/(authenticated)/articles': typeof authenticatedArticlesRoute
  '/(authenticated)/home': typeof authenticatedHomeRoute
  '/(authenticated)/mentors': typeof authenticatedMentorsRoute
  '/(authenticated)/notifications': typeof authenticatedNotificationsRoute
  '/(authenticated)/profile': typeof authenticatedProfileRoute
  '/(authenticated)/sessions': typeof authenticatedSessionsRoute
  '/admin/': typeof AdminIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/unauthorized/': typeof UnauthorizedIndexRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
  '/admin/expertisemanagement/': typeof AdminExpertisemanagementIndexRoute
  '/admin/mentormanagement/': typeof AdminMentormanagementIndexRoute
  '/admin/usermanagement/': typeof AdminUsermanagementIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/about'
    | '/articles'
    | '/home'
    | '/mentors'
    | '/notifications'
    | '/profile'
    | '/sessions'
    | '/admin/'
    | '/auth/'
    | '/unauthorized'
    | '/admin/dashboard'
    | '/admin/expertisemanagement'
    | '/admin/mentormanagement'
    | '/admin/usermanagement'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/articles'
    | '/home'
    | '/mentors'
    | '/notifications'
    | '/profile'
    | '/sessions'
    | '/admin'
    | '/auth'
    | '/unauthorized'
    | '/admin/dashboard'
    | '/admin/expertisemanagement'
    | '/admin/mentormanagement'
    | '/admin/usermanagement'
  id:
    | '__root__'
    | '/'
    | '/(authenticated)'
    | '/admin'
    | '/auth'
    | '/about'
    | '/(authenticated)/articles'
    | '/(authenticated)/home'
    | '/(authenticated)/mentors'
    | '/(authenticated)/notifications'
    | '/(authenticated)/profile'
    | '/(authenticated)/sessions'
    | '/admin/'
    | '/auth/'
    | '/unauthorized/'
    | '/admin/dashboard/'
    | '/admin/expertisemanagement/'
    | '/admin/mentormanagement/'
    | '/admin/usermanagement/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authenticatedRouteRoute: typeof authenticatedRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  UnauthorizedIndexRoute: typeof UnauthorizedIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)': {
      id: '/(authenticated)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized/': {
      id: '/unauthorized/'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/(authenticated)/sessions': {
      id: '/(authenticated)/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof authenticatedSessionsRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/profile': {
      id: '/(authenticated)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof authenticatedProfileRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/notifications': {
      id: '/(authenticated)/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof authenticatedNotificationsRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/mentors': {
      id: '/(authenticated)/mentors'
      path: '/mentors'
      fullPath: '/mentors'
      preLoaderRoute: typeof authenticatedMentorsRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/home': {
      id: '/(authenticated)/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof authenticatedHomeRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/articles': {
      id: '/(authenticated)/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof authenticatedArticlesRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/admin/usermanagement/': {
      id: '/admin/usermanagement/'
      path: '/usermanagement'
      fullPath: '/admin/usermanagement'
      preLoaderRoute: typeof AdminUsermanagementIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/mentormanagement/': {
      id: '/admin/mentormanagement/'
      path: '/mentormanagement'
      fullPath: '/admin/mentormanagement'
      preLoaderRoute: typeof AdminMentormanagementIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/expertisemanagement/': {
      id: '/admin/expertisemanagement/'
      path: '/expertisemanagement'
      fullPath: '/admin/expertisemanagement'
      preLoaderRoute: typeof AdminExpertisemanagementIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/dashboard/': {
      id: '/admin/dashboard/'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface authenticatedRouteRouteChildren {
  authenticatedArticlesRoute: typeof authenticatedArticlesRoute
  authenticatedHomeRoute: typeof authenticatedHomeRoute
  authenticatedMentorsRoute: typeof authenticatedMentorsRoute
  authenticatedNotificationsRoute: typeof authenticatedNotificationsRoute
  authenticatedProfileRoute: typeof authenticatedProfileRoute
  authenticatedSessionsRoute: typeof authenticatedSessionsRoute
}

const authenticatedRouteRouteChildren: authenticatedRouteRouteChildren = {
  authenticatedArticlesRoute: authenticatedArticlesRoute,
  authenticatedHomeRoute: authenticatedHomeRoute,
  authenticatedMentorsRoute: authenticatedMentorsRoute,
  authenticatedNotificationsRoute: authenticatedNotificationsRoute,
  authenticatedProfileRoute: authenticatedProfileRoute,
  authenticatedSessionsRoute: authenticatedSessionsRoute,
}

const authenticatedRouteRouteWithChildren =
  authenticatedRouteRoute._addFileChildren(authenticatedRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute
  AdminExpertisemanagementIndexRoute: typeof AdminExpertisemanagementIndexRoute
  AdminMentormanagementIndexRoute: typeof AdminMentormanagementIndexRoute
  AdminUsermanagementIndexRoute: typeof AdminUsermanagementIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
  AdminExpertisemanagementIndexRoute: AdminExpertisemanagementIndexRoute,
  AdminMentormanagementIndexRoute: AdminMentormanagementIndexRoute,
  AdminUsermanagementIndexRoute: AdminUsermanagementIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authenticatedRouteRoute: authenticatedRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  UnauthorizedIndexRoute: UnauthorizedIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
