/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UnauthorizedIndexRouteImport } from './routes/unauthorized/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminUsermanagementIndexRouteImport } from './routes/admin/usermanagement/index'
import { Route as AdminMentormanagementIndexRouteImport } from './routes/admin/mentormanagement/index'
import { Route as AdminExpertisemanagementIndexRouteImport } from './routes/admin/expertisemanagement/index'
import { Route as AdminDashboardIndexRouteImport } from './routes/admin/dashboard/index'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedIndexRoute = UnauthorizedIndexRouteImport.update({
  id: '/unauthorized/',
  path: '/unauthorized/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsermanagementIndexRoute =
  AdminUsermanagementIndexRouteImport.update({
    id: '/usermanagement/',
    path: '/usermanagement/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminMentormanagementIndexRoute =
  AdminMentormanagementIndexRouteImport.update({
    id: '/mentormanagement/',
    path: '/mentormanagement/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminExpertisemanagementIndexRoute =
  AdminExpertisemanagementIndexRouteImport.update({
    id: '/expertisemanagement/',
    path: '/expertisemanagement/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminDashboardIndexRoute = AdminDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/admin/': typeof AdminIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/unauthorized': typeof UnauthorizedIndexRoute
  '/admin/dashboard': typeof AdminDashboardIndexRoute
  '/admin/expertisemanagement': typeof AdminExpertisemanagementIndexRoute
  '/admin/mentormanagement': typeof AdminMentormanagementIndexRoute
  '/admin/usermanagement': typeof AdminUsermanagementIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminIndexRoute
  '/auth': typeof AuthIndexRoute
  '/unauthorized': typeof UnauthorizedIndexRoute
  '/admin/dashboard': typeof AdminDashboardIndexRoute
  '/admin/expertisemanagement': typeof AdminExpertisemanagementIndexRoute
  '/admin/mentormanagement': typeof AdminMentormanagementIndexRoute
  '/admin/usermanagement': typeof AdminUsermanagementIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/admin/': typeof AdminIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/unauthorized/': typeof UnauthorizedIndexRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
  '/admin/expertisemanagement/': typeof AdminExpertisemanagementIndexRoute
  '/admin/mentormanagement/': typeof AdminMentormanagementIndexRoute
  '/admin/usermanagement/': typeof AdminUsermanagementIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/about'
    | '/admin/'
    | '/auth/'
    | '/unauthorized'
    | '/admin/dashboard'
    | '/admin/expertisemanagement'
    | '/admin/mentormanagement'
    | '/admin/usermanagement'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/unauthorized'
    | '/admin/dashboard'
    | '/admin/expertisemanagement'
    | '/admin/mentormanagement'
    | '/admin/usermanagement'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/about'
    | '/admin/'
    | '/auth/'
    | '/unauthorized/'
    | '/admin/dashboard/'
    | '/admin/expertisemanagement/'
    | '/admin/mentormanagement/'
    | '/admin/usermanagement/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  UnauthorizedIndexRoute: typeof UnauthorizedIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized/': {
      id: '/unauthorized/'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/usermanagement/': {
      id: '/admin/usermanagement/'
      path: '/usermanagement'
      fullPath: '/admin/usermanagement'
      preLoaderRoute: typeof AdminUsermanagementIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/mentormanagement/': {
      id: '/admin/mentormanagement/'
      path: '/mentormanagement'
      fullPath: '/admin/mentormanagement'
      preLoaderRoute: typeof AdminMentormanagementIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/expertisemanagement/': {
      id: '/admin/expertisemanagement/'
      path: '/expertisemanagement'
      fullPath: '/admin/expertisemanagement'
      preLoaderRoute: typeof AdminExpertisemanagementIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/dashboard/': {
      id: '/admin/dashboard/'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute
  AdminExpertisemanagementIndexRoute: typeof AdminExpertisemanagementIndexRoute
  AdminMentormanagementIndexRoute: typeof AdminMentormanagementIndexRoute
  AdminUsermanagementIndexRoute: typeof AdminUsermanagementIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
  AdminExpertisemanagementIndexRoute: AdminExpertisemanagementIndexRoute,
  AdminMentormanagementIndexRoute: AdminMentormanagementIndexRoute,
  AdminUsermanagementIndexRoute: AdminUsermanagementIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  UnauthorizedIndexRoute: UnauthorizedIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
